# @package _group_
name: PNA
norm: false
loop: false
params:

  ppi:
    architecture:
      num_layers: 5
      hidden_channels: 2048
      aggregators: ['mean']
      scalers: ['identity', 'amplification']
      dropout: 0.2
      drop_input: true
      batch_norm: true
      residual: true
    num_parts: 20
    batch_size: 2
    max_steps: 10
    pool_size: 2
    num_workers: 0
    lr: 0.001
    reg_weight_decay: 0.0
    nonreg_weight_decay: 0.0
    grad_norm: 1.0
    epochs: 300

  arxiv:
    architecture:
      num_layers: 3
      hidden_channels: 256
      aggregators: ['mean']
      scalers: ['identity', 'amplification']
      dropout: 0.5
      drop_input: false
      batch_norm: true
      residual: false
    num_parts: 40
    batch_size: 20
    max_steps: 2
    pool_size: 2
    num_workers: 0
    lr: 0.005
    reg_weight_decay: 0.0
    nonreg_weight_decay: 0.0
    grad_norm: null
    epochs: 500

  flickr:
    architecture:
      num_layers: 4
      hidden_channels: 64
      aggregators: ['mean', 'max']
      scalers: ['identity', 'amplification']
      dropout: 0.5
      drop_input: true
      batch_norm: true
      residual: false
    num_parts: 24
    batch_size: 12
    max_steps: 2
    pool_size: 2
    num_workers: 0
    lr: 0.005
    reg_weight_decay: 0
    nonreg_weight_decay: 0
    grad_norm: null
    epochs: 500

  yelp:
    architecture:
      num_layers: 3
      hidden_channels: 512
      aggregators: ['mean']
      scalers: ['identity', 'amplification']
      dropout: 0.0
      drop_input: false
      batch_norm: false
      residual: true
    num_parts: 40
    batch_size: 5
    max_steps: 4
    pool_size: 2
    num_workers: 0
    lr: 0.005
    reg_weight_decay: 0.0
    nonreg_weight_decay: 0.0
    grad_norm: 1.0
    epochs: 400

  products:
    architecture:
      num_layers: 3
      hidden_channels: 256
      aggregators: ['mean']
      scalers: ['identity', 'amplification']
      dropout: 0.3
      drop_input: false
      batch_norm: false
      residual: false
    edge_dropout: 0.8
    num_parts: 150
    batch_size: 1
    max_steps: 151
    pool_size: 1
    num_workers: 0
    lr: 0.001
    reg_weight_decay: 0
    nonreg_weight_decay: 0
    grad_norm: null
    epochs: 150
    runs: 1
